### ISSUE TITLE
Issue-question-candidate

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cocode#10]
Automated Review Comments
Issues in main.py:
  - (6, 'Line exceeds 80 characters')
  - (16, 'Missing docstring for function')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (202, 'Hardcoded string found')
Issues in modules/ai_models.py:
  - (4, 'Missing docstring for function')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
