### ISSUE TITLE
Issue-some-fixes

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cocode#13]
Automated Review Comments
Issues in main.py:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Missing docstring for function')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
Issues in modules/database.py:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Missing docstring for function')
  - (27, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
