### ISSUE TITLE
Issue-v0 final

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cocode#18]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in main.py:
  - (2, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
