### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cocode#2]
Automated Review Comments
Issues in LICENSE:
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (199, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
