### ISSUE TITLE
Issue-initial-app

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cocode#4]
Automated Review Comments
Issues in main.py:
  - (6, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
Issues in modules/ai_models.py:
  - (17, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
Issues in modules/database.py:
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
Issues in modules/resume.py:
  - (19, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
Issues in modules/tempfile_util.py:
  - (9, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
